FROM alpine/java:21

ENV KEYCLOAK_VERSION=999.0.0-SNAPSHOT
ENV KEYCLOAK_HOME=/opt/keycloak

WORKDIR $KEYCLOAK_HOME

COPY /quarkus/dist/target/keycloak-$KEYCLOAK_VERSION.zip $KEYCLOAK_HOME

RUN unzip keycloak-$KEYCLOAK_VERSION.zip

WORKDIR $KEYCLOAK_HOME/keycloak-$KEYCLOAK_VERSION